workflows:
  ios-native-workflow:
    name: Build Native Apple App (iOS, iPadOS, macOS)
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      xcode: latest
    scripts:
      - name: Build iOS & iPadOS App
        script: |
          cd ZionStageApple
          xcodebuild -quiet -project ZionStageApple.xcodeproj -scheme ZionStageApple -sdk iphonesimulator -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
      - name: Build macOS App
        script: |
          cd ZionStageApple
          xcodebuild -quiet -project ZionStageApple.xcodeproj -scheme ZionStageApple -sdk macosx -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    artifacts:
      - ZionStageApple/build/Release-iphonesimulator/*.app
      - ZionStageApple/build/Release/*.app
